version: "3.8"

services:
  whisper-live-kit:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: wlk
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["--model", "base", "--language", "en"]
